name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  dio: ^5.4.0
  url_launcher: ^6.3.0
  http: ^1.2.0
  flutter_downloader: ^1.11.6
  path_provider: ^2.1.2
  permission_handler: ^11.3.1


  # Firebase (uncomment if needed)
  # firebase_core: ^latest
  # firebase_auth: ^latest
  # cloud_firestore: ^latest
  # firebase_messaging: ^latest

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
